R"grammar(
    root            = identifier* __
    identifier      = __ [a-zA-Z_$] [a-zA-Z_$0-9]*

    __              = (spacing | comment | directive)*
    spacing         = [ \t\r\n]+
    comment         = line_comment | block_comment
    line_comment    = '//' (!eofl .)*
    block_comment   = '/*' (!'*/' .)* '*/'
    directive       = '#' (!eofl ('\\' eofl | .))*

    eofl            = eof | eol
    eol             = '\r\n' | '\n'
    eof             = !.
)grammar"

